services:

  lite-server:
    build:
      context: "../task-2"
      dockerfile: "./Dockerfile"
    entrypoint: ["lite-server", "-c", "bs-config.json"]
    volumes:
      - /home/fort/IASA_Highload/lab1-docker/task-2/static:/app/static
      - /home/fort/IASA_Highload/lab1-docker/task-2/bs-config.json:/app/bs-config.json
    deploy:
      mode: replicated
      replicas: 3
    expose:
      - "3000"

  json-server:
    build:
      context: "../task-3"
      dockerfile: "./Dockerfile"
    entrypoint: ["json-server", "--watch", "db.json", "--host", "0.0.0.0", "--port", "3001"]
    volumes:
      - /home/fort/IASA_Highload/lab1-docker/task-3/db.json:/app/db.json
    deploy:
      mode: replicated
      replicas: 3
    expose:
      - "3001"

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /home/fort/IASA_Highload/lab1-docker/task-4/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - lite-server
      - json-server
